### ISSUE TITLE
The onTap on Inkwell widgets doesn't work

### ISSUE THREAD

**Issue by francescofact** [iamadeeb/Flutter-Meditation-App#1]
Hi, 
The onTap function in the InkWell created by DiscoverSmallCard doesn't fire onTap, but it gets set correctly.
Do you have a fix?

**Comment by iamadeeb** [comment]
Can you please specify the exact part of the code?

**Comment by francescofact** [comment]
in "/lib/dicover_page.dart" when there are the DiscoverSmallCard widgets the function inside the onTap var is not executed.
ex if I add a print inside the event and I tap on the card it doesn't print anything.
```
DiscoverSmallCard(
                    onTap: () { print("hello world");},
```

**Comment by iamadeeb** [comment]
I just pushed a fix, please check
